MAX_LIMIT = 1000
VALID_PAYMENT_METHODS = {"cod", "upi", "card", "netbanking"}
GIFT_PACKAGING_PRICE = 149

PAYMENT_PROVIDER_CASHFREE = "cashfree"
PAYMENT_PROVIDER_MANUAL_LEGACY = "manual_legacy"

PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_EXPIRED = "expired"
PAYMENT_STATUS_REFUNDED = "refunded"
VALID_PAYMENT_STATUSES = {
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_EXPIRED,
    PAYMENT_STATUS_REFUNDED,
}

ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_PENDING_PAYMENT = "pending_payment"
ORDER_STATUS_PAYMENT_FAILED = "payment_failed"
ORDER_STATUS_PAYMENT_EXPIRED = "payment_expired"
ORDER_STATUS_PAID_STOCK_ISSUE = "paid_stock_issue"
ORDER_STATUS_CONFIRMED = "confirmed"
ORDER_STATUS_PACKED = "packed"
ORDER_STATUS_SHIPPED = "shipped"
ORDER_STATUS_DELIVERED = "delivered"
ORDER_STATUS_CANCELLED = "cancelled"

PAID_ORDER_STATUSES = {
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_PACKED,
    ORDER_STATUS_SHIPPED,
    ORDER_STATUS_DELIVERED,
}

FAILED_ORDER_STATUSES = {
    ORDER_STATUS_PAYMENT_FAILED,
    ORDER_STATUS_PAYMENT_EXPIRED,
    ORDER_STATUS_CANCELLED,
}

CASHFREE_ORDER_STATUS_ACTIVE = "ACTIVE"
CASHFREE_ORDER_STATUS_PAID = "PAID"
CASHFREE_ORDER_STATUS_EXPIRED = "EXPIRED"
CASHFREE_ORDER_STATUS_TERMINATED = "TERMINATED"
CASHFREE_ORDER_STATUS_TERMINATION_REQUESTED = "TERMINATION_REQUESTED"
